---
- hosts: all
  # become: true
  # become_user: root
  tasks:
  - name: "Runing the CMD. "
    shell: "echo 'hello!!\n world of ansible.\n Well done dnyanesh'"
    args:
      executable: /usr/bin/bash
    register: file_content

  - name: "Print the CMD content to a console"
    debug:
      msg: "{{ file_content.stdout_lines    }}"
  - name: "Print the error content of CMD to a console"
    debug:
      msg: "{{ file_content.stderr   }}"

