---
- hosts: all
  tasks:
  - name: "Read a file content"
    shell: cat /etc/hosts
    register: file_content

  - name: "Print the file content to a console"
    debug:
      msg: "{{ file_content.stdout_lines    }}"
