---
- hosts: all
  tasks:
  - name: "Read a file content"
    shell: ping  -c 1 -w 2 5.5.5.5
    register: file_content

  - name: "Print the ping contain to send only 1 pkg content to a console"
    debug:
      msg: "{{ file_content.stdout_lines    }}"
